doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Nanny:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/BoundedContext/Nanny/Infra/Mapping'
                prefix: 'App\BoundedContext\Nanny\Domain\Model'
                alias: App
#            Family:
#                is_bundle: false
#                type: xml
#                dir: '%kernel.project_dir%/src/BoundedContext/Family/Domain/Model'
#                prefix: 'App\Family'
#                alias: App