# config/packages/security.yaml
security:
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: true
      lazy: true
  encoders:
    App\BoundedContext\Nanny\App\Domain\Model\Nanny:
      algorithm: auto