{
    "swagger": "2.0",
    "info": {
        "title": "Attache-Nounou",
        "description": "",
        "termsOfService": "terms",
        "contact": {
            "name": "a.sparesotto@icloud.com"
        },
        "license": {
            "name": "proprietary"
        },
        "version": "1.0"
    },
    "host": "localhost:80",
    "basePath": "/attache-nounou/nanny/create",
    "schemes": [
        "http"
    ],
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "paths": {
        "/attache-nounou/nanny/create": {
            "post": {
                "tags": [
                    "Nanny"
                ],
                "summary": "Create account nanny",
                "description": "",
                "operationId": "create_nanny",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "description": "creation of the nanny account",
                        "required": true,
                        "schema": {
                            "properties": {
                                "lastname": {
                                    "type": "string",
                                    "example": "Sparesotto"
                                },
                                "firstname": {
                                    "type": "string",
                                    "example": "Anais"
                                },
                                "birthday": {
                                    "type": "string",
                                    "example": "1991-04-25"
                                },
                                "phoneNumber": {
                                    "type": "string",
                                    "example": "0671259957"
                                },
                                "adresse": {
                                    "type": "string",
                                    "example": "10 rue emile Combes"
                                },
                                "postalCode": {
                                    "type": "string",
                                    "example": "83149"
                                },
                                "city": {
                                    "type": "string",
                                    "example": "Bras"
                                },
                                "function": {
                                    "type": "string",
                                    "example": "Assmat"
                                },
                                "email": {
                                    "type": "string",
                                    "example": "a.sparesotto@icloud.com"
                                },
                                "password": {
                                    "type": "string",
                                    "example": "1234"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {}
}